"""Init

Revision ID: 4c1150dddfe5
Revises: 
Create Date: 2026-03-27 23:06:43.617612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1150dddfe5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Enum('infraestructura', 'alumbrado', 'residuos', 'trafico', 'zonas_verdes', 'otro', name='categoriaenum'), nullable=False),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridadenum'), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'en_progreso', 'resuelta', 'rechazada', name='estadoenum'), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_id'), 'incidencias', ['id'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('abierta', 'en_progreso', 'resuelta', 'rechazada', name='estadoenum'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('abierta', 'en_progreso', 'resuelta', 'rechazada', name='estadoenum'), nullable=False),
    sa.Column('cambiado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenes_id'), 'imagenes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imagenes_id'), table_name='imagenes')
    op.drop_table('imagenes')
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_incidencias_id'), table_name='incidencias')
    op.drop_table('incidencias')
    # ### end Alembic commands ###
