import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  addCircleOutline,
  alertCircleOutline,
  arrowForwardOutline,
  bulbOutline,
  businessOutline,
  cameraOutline,
  chatbubbleEllipsesOutline,
  checkmarkCircleOutline,
  checkmarkOutline,
  chevronForwardOutline,
  closeOutline,
  constructOutline,
  createOutline,
  documentTextOutline,
  folderOpenOutline,
  gridOutline,
  homeOutline,
  imageOutline,
  informationCircleOutline,
  locateOutline,
  locationOutline,
  lockClosedOutline,
  logoFacebook,
  logoGithub,
  logoInstagram,
  logoTwitter,
  mapOutline,
  menuOutline,
  notificationsOutline,
  peopleCircleOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  radioOutline,
  shieldCheckmarkOutline,
  statsChartOutline,
  trashOutline,
} from 'ionicons/icons';
import { provideHttpClient, withInterceptors } from '@angular/common/http';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { authInterceptor } from './app/interceptors/auth.interceptor';

addIcons({
  addCircleOutline,
  alertCircleOutline,
  arrowForwardOutline,
  bulbOutline,
  businessOutline,
  cameraOutline,
  chatbubbleEllipsesOutline,
  checkmarkCircleOutline,
  checkmarkOutline,
  chevronForwardOutline,
  closeOutline,
  constructOutline,
  createOutline,
  documentTextOutline,
  folderOpenOutline,
  gridOutline,
  homeOutline,
  imageOutline,
  informationCircleOutline,
  locateOutline,
  locationOutline,
  lockClosedOutline,
  logoFacebook,
  logoGithub,
  logoInstagram,
  logoTwitter,
  mapOutline,
  menuOutline,
  notificationsOutline,
  peopleCircleOutline,
  peopleOutline,
  personAddOutline,
  personCircleOutline,
  radioOutline,
  shieldCheckmarkOutline,
  statsChartOutline,
  trashOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(withInterceptors([authInterceptor])),
  ],
});
